// <auto-generated />
using System;
using CiftciSatis.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CiftciSatis.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210409123350_database-build")]
    partial class databasebuild
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CiftciSatis.Data.Models.Ciftci", b =>
                {
                    b.Property<int>("CiftciId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CiftciAd");

                    b.Property<string>("CiftciAdres");

                    b.Property<double>("CiftciBakiye");

                    b.Property<string>("CiftciEmail");

                    b.Property<string>("CiftciSifre");

                    b.Property<string>("CiftciSoyad");

                    b.HasKey("CiftciId");

                    b.ToTable("Ciftcis");
                });

            modelBuilder.Entity("CiftciSatis.Data.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MusteriAd");

                    b.Property<string>("MusteriAdres");

                    b.Property<double>("MusteriBakiye");

                    b.Property<string>("MusteriEmail");

                    b.Property<string>("MusteriSifre");

                    b.Property<string>("MusteriSoyad");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteris");
                });

            modelBuilder.Entity("CiftciSatis.Data.Models.Siparisler", b =>
                {
                    b.Property<int>("SiparisId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CiftciId");

                    b.Property<int>("MusteriId");

                    b.Property<DateTime>("SiparisKTarih");

                    b.Property<int>("SiparisMiktar");

                    b.Property<double>("SiparisTutar");

                    b.Property<int>("UrunId");

                    b.HasKey("SiparisId");

                    b.HasIndex("CiftciId");

                    b.ToTable("Siparislers");
                });

            modelBuilder.Entity("CiftciSatis.Data.Models.Urunler", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CiftciId");

                    b.Property<string>("UrunAd");

                    b.Property<double>("UrunFiyat");

                    b.Property<DateTime>("UrunKTarih");

                    b.Property<int>("UrunMiktar");

                    b.Property<int>("UrunRandıman");

                    b.Property<string>("UrunRenk");

                    b.Property<string>("UrunTur");

                    b.HasKey("UrunId");

                    b.HasIndex("CiftciId");

                    b.ToTable("Urunlers");
                });

            modelBuilder.Entity("CiftciSatis.Data.Models.Siparisler", b =>
                {
                    b.HasOne("CiftciSatis.Data.Models.Ciftci", "Ciftci")
                        .WithMany("Siparislers")
                        .HasForeignKey("CiftciId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CiftciSatis.Data.Models.Urunler", b =>
                {
                    b.HasOne("CiftciSatis.Data.Models.Ciftci")
                        .WithMany("Urunlers")
                        .HasForeignKey("CiftciId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
